[settings]
frequency = 600
timescale = 1

[[enteties]]
primary = true

[enteties.sprite]
path = "./cube.glb"
label = "Scene0"

[[enteties]]

[enteties.sprite]
path = "../assets/arrow.glb"
label = "Scene0"


# Mass::new(0.023),
# Inertia::cylinder_x(0.71, 0.3 / 100., 0.023),
