name: Check

on: [push, pull_request]



jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libasound2-dev libudev-dev
        version: 1.0

    - name: build
      run: cargo build --verbose

    - name: tests
      run: cargo test --workspace --verbose
