name: Check

on: [push, pull_request]



jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libasound2-dev libudev-dev
        version: 1.0
                  
    - uses: actions/cache@v4.0.2
      with:
        path: |
          ${{ github.workspace }}/target
          ~/.cargo/registry
        key: ${{ runner.os }}-debug-build-${{ hashFiles('./Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-debug-build-
          ${{ runner.os }}-

    - name: build
      run: cargo build --verbose

    - name: tests
      run: cargo test --workspace --verbose
