name: Check

on: [push, pull_request]

jobs:
  build-debug:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Load caches
      uses: ./.github/cargo-setup

    - name: build
      run: cargo build --verbose



  tests:
    name: Run tests
    needs: build-debug
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Load caches
      uses: ./.github/cargo-setup

    - name: Lib tests
      run: cargo test --workspace --verbose --lib

    - name: Doc tests
      run: cargo test --workspace --verbose --doc



  clippy:
    name: Check formatting
    needs: build-debug
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Load caches
      uses: ./.github/cargo-setup

    - name: Lint
      run: cargo clippy -- -D warnings
